cShareSystems.load_pas("WPMarshall's Map Pack", [
	"coui://ui/mods/wpmarshall/systems/(1v1)_smelter.pas",
	"coui://ui/mods/wpmarshall/systems/(1v1)_lugaan.pas",
	"coui://ui/mods/wpmarshall/systems/(1v1)_derisia.pas",
	"coui://ui/mods/wpmarshall/systems/(1v1)_oblivarum.pas",
	"coui://ui/mods/wpmarshall/systems/(1v1)_moore.pas",
	"coui://ui/mods/wpmarshall/systems/finn's_resurgence.pas",	
	"coui://ui/mods/wpmarshall/systems/solitude.pas",	
	"coui://ui/mods/wpmarshall/systems/pressure_cooker.pas",	
	"coui://ui/mods/wpmarshall/systems/(2v2)_boading.pas",
	"coui://ui/mods/wpmarshall/systems/kinomo.pas",	
	"coui://ui/mods/wpmarshall/systems/monsoon.pas",	
	"coui://ui/mods/wpmarshall/systems/fields_of isis.pas",	
	"coui://ui/mods/wpmarshall/systems/cauldron.pas",	
	"coui://ui/mods/wpmarshall/systems/singe.pas",	
	"coui://ui/mods/wpmarshall/systems/cratered.pas",	
	"coui://ui/mods/wpmarshall/systems/shipyards.pas",
	"coui://ui/mods/wpmarshall/systems/outlier.pas",	
	"coui://ui/mods/wpmarshall/systems/seton's_grip.pas",	
	"coui://ui/mods/wpmarshall/systems/station_sigma.pas",	
	"coui://ui/mods/wpmarshall/systems/station_sigma (5v5 unshared).pas",	
	"coui://ui/mods/wpmarshall/systems/station_sigma (ffa).pas",		
	"coui://ui/mods/wpmarshall/systems/tandem.pas",	
	"coui://ui/mods/wpmarshall/systems/quandary.pas",	
	"coui://ui/mods/wpmarshall/systems/doomball.pas",	
	"coui://ui/mods/wpmarshall/systems/realm_battlegrounds.pas",	
	"coui://ui/mods/wpmarshall/systems/the_able conglomerate.pas",	
	"coui://ui/mods/wpmarshall/systems/sorian's_supper.pas",	
	"coui://ui/mods/wpmarshall/systems/final_destination.pas",	
	"coui://ui/mods/wpmarshall/systems/marshall's_lament (classic).pas",
	"coui://ui/mods/wpmarshall/systems/marshall's_lament (redux).pas",
	"coui://ui/mods/wpmarshall/systems/marshall's_lament (titans).pas",
	"coui://ui/mods/wpmarshall/systems/cosmic_chaos (15 players max).pas",
	"coui://ui/mods/wpmarshall/systems/(10p_ffa) gladiator's forum deluxe.pas",
	"coui://ui/mods/wpmarshall/systems/(shared) gladiator's forum deluxe.pas",	
	"coui://ui/mods/wpmarshall/systems/diskus_(teams).pas",	
	"coui://ui/mods/wpmarshall/systems/diskus_(ffa).pas",	
	"coui://ui/mods/wpmarshall/systems/hollow_lanes.pas",	
	"coui://ui/mods/wpmarshall/systems/cubic_combat.pas",	
	"coui://ui/mods/wpmarshall/systems/world_of tomorrow 2.1.0.pas",	
	
]);
cShareSystems.load_pas("HEMISPHERIC Maps", [
	"coui://ui/mods/wpmarshall/systems/thief's_pass.pas",	
	"coui://ui/mods/wpmarshall/systems/shoreline.pas",	
	"coui://ui/mods/wpmarshall/systems/four_corners.pas",	
	"coui://ui/mods/wpmarshall/systems/five-leaf_clover.pas",	
	"coui://ui/mods/wpmarshall/systems/finn's_resurgence.pas",	
	"coui://ui/mods/wpmarshall/systems/fields_of isis.pas",	
	"coui://ui/mods/wpmarshall/systems/doomball.pas",	
	
]);