cShareSystems.load_pas("WPMarshall", [

	"coui://ui/mods/wpmarshall/systems/(1v1)_derisia.pas",
	"coui://ui/mods/wpmarshall/systems/(1v1)_kinomo.pas",
	"coui://ui/mods/wpmarshall/systems/(1v1)_moore.pas",
	"coui://ui/mods/wpmarshall/systems/(1v1)_oblivarum.pas",
	"coui://ui/mods/wpmarshall/systems/(1v1)_pressure_cooker.pas",
	"coui://ui/mods/wpmarshall/systems/(1v1)_smelter.pas",
	"coui://ui/mods/wpmarshall/systems/(1v1)_solitude.pas",
	"coui://ui/mods/wpmarshall/systems/HEM_(1v1)_finn's_resurgence.pas",
	"coui://ui/mods/wpmarshall/systems/HEM_(2v2)_fields_of isis.pas",
	"coui://ui/mods/wpmarshall/systems/(1v1)_boading.pas",
	"coui://ui/mods/wpmarshall/systems/(1v1)_cauldron.pas",
	"coui://ui/mods/wpmarshall/systems/(1v1)_monsoon.pas",
	"coui://ui/mods/wpmarshall/systems/(2v2)_conductor.pas",
	"coui://ui/mods/wpmarshall/systems/(2shared)_cratered.pas",
	"coui://ui/mods/wpmarshall/systems/(2shared)_outlier.pas",
	"coui://ui/mods/wpmarshall/systems/(2shared)_shipyards.pas",
	"coui://ui/mods/wpmarshall/systems/(2shared)_snowball.pas",
	"coui://ui/mods/wpmarshall/systems/(4v4)_seton's_clutch.pas",
	"coui://ui/mods/wpmarshall/systems/(5v5)_station_sigma.pas",
	"coui://ui/mods/wpmarshall/systems/(5unshared)_station_sigma (5v5 unshared).pas",
	"coui://ui/mods/wpmarshall/systems/(5v5)_marshall's_lament (classic).pas",
	"coui://ui/mods/wpmarshall/systems/(5v5)_marshall's_lament (redux).pas",
	"coui://ui/mods/wpmarshall/systems/(5v5)_marshall's_lament (titans).pas",
	"coui://ui/mods/wpmarshall/systems/(3p_ffa)_quandary.pas",
	"coui://ui/mods/wpmarshall/systems/(4p_ffa)_tandem.pas",
	"coui://ui/mods/wpmarshall/systems/(4p_ffa)_the_able conglomerate.pas",
	"coui://ui/mods/wpmarshall/systems/(4p_ffa)_sorian's_supper.pas",
	"coui://ui/mods/wpmarshall/systems/(4p_ffa)_final_destination.pas",
	"coui://ui/mods/wpmarshall/systems/(4p_ffa)_marshall's_legacy.pas",
	"coui://ui/mods/wpmarshall/systems/(4p_ffa)_the_great scuffle.pas",
	"coui://ui/mods/wpmarshall/systems/(5p_ffa)_station_sigma (ffa).pas",
	"coui://ui/mods/wpmarshall/systems/HEM_(5p_ffa)_doomball.pas",	
	"coui://ui/mods/wpmarshall/systems/(6p_ffa)_hollow_lanes.pas",
	"coui://ui/mods/wpmarshall/systems/(7p_ffa)_the_sift.pas",	
	"coui://ui/mods/wpmarshall/systems/(8p_ffa)_realm_battlegrounds.pas",
	"coui://ui/mods/wpmarshall/systems/(15p_ffa)_cosmic_chaos (15 players max).pas",
	"coui://ui/mods/wpmarshall/systems/(10p_ffa)_gladiator's forum deluxe.pas",
	"coui://ui/mods/wpmarshall/systems/(2shared)_gladiator's forum deluxe.pas",
	"coui://ui/mods/wpmarshall/systems/(2shared)_diskus_(teams).pas",
	"coui://ui/mods/wpmarshall/systems/(4p_ffa)_diskus_(ffa).pas",
	"coui://ui/mods/wpmarshall/systems/(6p_ffa)_cubic_combat.pas",
	"coui://ui/mods/wpmarshall/systems/(5v5)_world_of tomorrow 2.1.0.pas",
	"coui://ui/mods/wpmarshall/systems/geography_palette.pas",
	
]);
cShareSystems.load_pas("HEMISPHERIC", [
	"coui://ui/mods/wpmarshall/systems/HEM_(1v1)_finn's_resurgence.pas",
	"coui://ui/mods/wpmarshall/systems/HEM_(1v1)_shoreline.pas",
	"coui://ui/mods/wpmarshall/systems/HEM_(2shared)_thief's_pass.pas",
	"coui://ui/mods/wpmarshall/systems/HEM_(2v2)_fields_of isis.pas",
	"coui://ui/mods/wpmarshall/systems/HEM_(4p_ffa)_four_corners.pas",
	"coui://ui/mods/wpmarshall/systems/HEM_(5p_ffa)_five-leaf_clover.pas",
	"coui://ui/mods/wpmarshall/systems/HEM_(5p_ffa)_doomball.pas",
	"coui://ui/mods/wpmarshall/systems/HEM_(2v2v2)_dark_heart.pas",
	
]);