cShareSystems.load_pas("WPMarshall's Map Pack", [
	"coui://ui/mods/wpmarshall/systems/(1v1)_smelter.pas",
	"coui://ui/mods/wpmarshall/systems/(1v1)_lugaan.pas",
	"coui://ui/mods/wpmarshall/systems/(1v1)_derisia.pas",
	"coui://ui/mods/wpmarshall/systems/(1v1)_oblivarum.pas",
	"coui://ui/mods/wpmarshall/systems/(1v1)_moore.pas",
	"coui://ui/mods/wpmarshall/systems/(2v2)_boading.pas",
	"coui://ui/mods/wpmarshall/systems/kinomo.pas",	
	"coui://ui/mods/wpmarshall/systems/cauldron.pas",	
	"coui://ui/mods/wpmarshall/systems/cratered.pas",	
	"coui://ui/mods/wpmarshall/systems/shipyards.pas",	
	"coui://ui/mods/wpmarshall/systems/tandem.pas",	
	"coui://ui/mods/wpmarshall/systems/quandary.pas",	
	"coui://ui/mods/wpmarshall/systems/marshall's_lament (classic).pas",
	"coui://ui/mods/wpmarshall/systems/marshall's_lament (redux).pas",
	"coui://ui/mods/wpmarshall/systems/marshall's_lament (titans).pas",
	"coui://ui/mods/wpmarshall/systems/gladiator's_forum redux.pas",
	"coui://ui/mods/wpmarshall/systems/gladiator's_forum redux (co-op).pas",	
	"coui://ui/mods/wpmarshall/systems/diskus_(teams).pas",	
	"coui://ui/mods/wpmarshall/systems/diskus_(ffa).pas",	
	"coui://ui/mods/wpmarshall/systems/hollow_lanes.pas",	
	"coui://ui/mods/wpmarshall/systems/cubic_combat.pas",	
	"coui://ui/mods/wpmarshall/systems/finn's_resurgence.pas",	
	"coui://ui/mods/wpmarshall/systems/fields_of isis.pas",	
	
]);